# **Section 2: Numpy**

### **Introduction**

Central objects: arrays

What Numpy can be used for?
* Matrix operations (addition, multiplication, etc.)
* Solving linear systems
* Calculating inverse and determinant of matrices
* Generate random numbers

Applications:
* Linear regression
* Logistic regression
* Deep neural networks
* K-means clustering
* Density estimation
* Principal components analysis
* Matrix factorization (recommender systems)
* Support vector machines
* Markov models
* Control systems
* Game theory
* Operation research
* Portfolio optimization

*Remark:* In Numpy, vectors are 1D (not an N x 1 ''2D array'')

### **Array vs. lists**

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [4]:
A = np.array([1,2,3])

In [5]:
for e in L:
  print(e)

1
2
3


In [6]:
for e in A:
  print(e)

1
2
3


In [7]:
L.append(4)

In [8]:
L

[1, 2, 3, 4]

Size of an array is fixed, no append method for array:

In [9]:
A.append(4)

AttributeError: ignored

Lists can be concatenated:

In [10]:
L + [5]

[1, 2, 3, 4, 5]

Arrays work differently, adds this element to all elements of A, this is called broadcasting:

In [11]:
A + np.array([4])

array([5, 6, 7])

When adding two same sized array, they are added up element-wise:

In [12]:
A + np.array([4,5,6])

array([5, 7, 9])

But broadcasting won't work when we try to add two different sized vector (none of them with length one):

In [13]:
A + np.array([4,5])

ValueError: ignored

Scalar multiplication works as expected in case of arrays:

In [14]:
2 * A

array([2, 4, 6])

But list gets repeated two times:

In [15]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

Using lists to add value to each element:

In [16]:
L2 = []
for e in L:
  L2.append(e+3)

In [17]:
L2

[4, 5, 6, 7]

Same with list comprehension:

In [18]:
L2 = [e + 3 for e in L]

In [19]:
L2

[4, 5, 6, 7]

This is pretty flexible, e.g. square every list element:

In [20]:
L2 = []
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

But using arrays, this is much easier:

In [21]:
A**2

array([1, 4, 9])

Functions mostly applied elementwise for arrays:

In [22]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [23]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

List looks like an array, but is a more general data structure. Numpy array exist for mathematics.