# **Section 2: Numpy** 
<a href="https://colab.research.google.com/github/osuranyi/UdemyCourses/blob/main/NumpyStack/Section2_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Introduction**

Central objects: arrays

What Numpy can be used for?
* Matrix operations (addition, multiplication, etc.)
* Solving linear systems
* Calculating inverse and determinant of matrices
* Generate random numbers

Applications:
* Linear regression
* Logistic regression
* Deep neural networks
* K-means clustering
* Density estimation
* Principal components analysis
* Matrix factorization (recommender systems)
* Support vector machines
* Markov models
* Control systems
* Game theory
* Operation research
* Portfolio optimization

*Remark:* In Numpy, vectors are 1D (not an N x 1 ''2D array'')

## **Array vs. lists**

In [ ]:
import numpy as np

In [ ]:
L = [1,2,3]

In [ ]:
A = np.array([1,2,3])

In [ ]:
for e in L:
  print(e)

1
2
3


In [ ]:
for e in A:
  print(e)

1
2
3


In [ ]:
L.append(4)

In [ ]:
L

[1, 2, 3, 4]

Size of an array is fixed, no append method for array:

In [ ]:
A.append(4)

AttributeError: ignored

Lists can be concatenated:

In [ ]:
L + [5]

[1, 2, 3, 4, 5]

Arrays work differently, adds this element to all elements of A, this is called broadcasting:

In [ ]:
A + np.array([4])

array([5, 6, 7])

When adding two same sized array, they are added up element-wise:

In [ ]:
A + np.array([4,5,6])

array([5, 7, 9])

But broadcasting won't work when we try to add two different sized vector (none of them with length one):

In [ ]:
A + np.array([4,5])

ValueError: ignored

Scalar multiplication works as expected in case of arrays:

In [ ]:
2 * A

array([2, 4, 6])

But list gets repeated two times:

In [ ]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

Using lists to add value to each element:

In [ ]:
L2 = []
for e in L:
  L2.append(e+3)

In [ ]:
L2

[4, 5, 6, 7]

Same with list comprehension:

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

[4, 5, 6, 7]

This is pretty flexible, e.g. square every list element:

In [ ]:
L2 = []
L2 = [e**2 for e in L]
L2

[1, 4, 9, 16]

But using arrays, this is much easier:

In [ ]:
A**2

array([1, 4, 9])

Functions mostly applied elementwise for arrays:

In [ ]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [ ]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

List looks like an array, but is a more general data structure. Numpy array exist for mathematics.

## **Dot product**

$$
a \cdot b = a^T b = \sum_{d=1}^D a_d b_d
$$

In [25]:
a = np.array([1,2])
b = np.array([3,4])

Performing dot product "by hand"

In [26]:
dot = 0
for e, f in zip(a,b):
  dot += e*f
dot

11

In [27]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

What happens if we use * operator?

In [28]:
a * b

array([3, 8])

Elementwise, but can be used to calculate dot product:

In [30]:
np.sum(a * b)

11

In [31]:
(a * b).sum()

11

Using the dedicated *dot* function:

In [32]:
np.dot(a,b)

11

Also works as an instance method:

In [33]:
a.dot(b)

11

The symbol @ also performs the dot product:

In [34]:
a @ b

11

Alternative definition of dot product:
$$
a^T b = \|a\| \, \|b\| \cos\theta
$$

In [37]:
amag = np.sqrt(a@a)
amag

2.23606797749979

In [39]:
np.linalg.norm(a)

2.23606797749979

In [40]:
cosangle = a@b / (np.linalg.norm(a) * np.linalg.norm(b))

In [41]:
angle = np.arccos(cosangle)
angle

0.17985349979247847